"""add character role_type column

Revision ID: 1fc8b9ef86fc
Revises: f059c9246c6d
Create Date: 2026-07-12 15:14:08.388729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc8b9ef86fc'
down_revision: Union[str, None] = 'f059c9246c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bubbles_panel_id'), 'bubbles', ['panel_id'], unique=False)
    op.create_index(op.f('ix_buildings_world_id'), 'buildings', ['world_id'], unique=False)
    op.create_index(op.f('ix_chapters_status'), 'chapters', ['status'], unique=False)
    op.add_column('characters', sa.Column('role_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_role_type'), 'characters', ['role_type'], unique=False)
    op.create_index(op.f('ix_images_panel_id'), 'images', ['panel_id'], unique=False)
    op.create_index(op.f('ix_images_prompt_id'), 'images', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_images_status'), 'images', ['status'], unique=False)
    op.create_index(op.f('ix_outfits_world_id'), 'outfits', ['world_id'], unique=False)
    op.create_index(op.f('ix_pages_chapter_id'), 'pages', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_panels_page_id'), 'panels', ['page_id'], unique=False)
    op.create_index(op.f('ix_panels_scene_id'), 'panels', ['scene_id'], unique=False)
    op.create_index(op.f('ix_panels_status'), 'panels', ['status'], unique=False)
    op.create_index(op.f('ix_props_world_id'), 'props', ['world_id'], unique=False)
    op.create_index(op.f('ix_scene_assets_world_id'), 'scene_assets', ['world_id'], unique=False)
    op.create_index(op.f('ix_scenes_chapter_id'), 'scenes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_scenes_status'), 'scenes', ['status'], unique=False)
    op.create_index(op.f('ix_shots_panel_id'), 'shots', ['panel_id'], unique=False)
    op.create_index(op.f('ix_style_templates_project_id'), 'style_templates', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_world_buildings_project_id'), 'world_buildings', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_buildings_project_id'), table_name='world_buildings')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_style_templates_project_id'), table_name='style_templates')
    op.drop_index(op.f('ix_shots_panel_id'), table_name='shots')
    op.drop_index(op.f('ix_scenes_status'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_chapter_id'), table_name='scenes')
    op.drop_index(op.f('ix_scene_assets_world_id'), table_name='scene_assets')
    op.drop_index(op.f('ix_props_world_id'), table_name='props')
    op.drop_index(op.f('ix_panels_status'), table_name='panels')
    op.drop_index(op.f('ix_panels_scene_id'), table_name='panels')
    op.drop_index(op.f('ix_panels_page_id'), table_name='panels')
    op.drop_index(op.f('ix_pages_chapter_id'), table_name='pages')
    op.drop_index(op.f('ix_outfits_world_id'), table_name='outfits')
    op.drop_index(op.f('ix_images_status'), table_name='images')
    op.drop_index(op.f('ix_images_prompt_id'), table_name='images')
    op.drop_index(op.f('ix_images_panel_id'), table_name='images')
    op.drop_index(op.f('ix_characters_role_type'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_column('characters', 'role_type')
    op.drop_index(op.f('ix_chapters_status'), table_name='chapters')
    op.drop_index(op.f('ix_buildings_world_id'), table_name='buildings')
    op.drop_index(op.f('ix_bubbles_panel_id'), table_name='bubbles')
    # ### end Alembic commands ###
